# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-29 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200629_1211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsLetterRecipients',
        ),
    ]
